// Generates styles/tokens.css from design/tokens.json. Run: npm run tokens -w apps/web
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'design/tokens.json'), 'utf8'));
const [light, dark] = tokens.color.themes.map((t) => t.id);

const ref = (v) => (typeof v === 'string' ? v.replace(/^\{([^}]+)\}$/, 'var(--$1)') : v);
const lines = { light: [], dark: [] };

for (const t of tokens.color.tokens) {
  const v = typeof t.value === 'string' ? { [light]: t.value } : t.value;
  lines.light.push(`  --${t.name}: ${ref(v[light])};`);
  if (v[dark] !== undefined && ref(v[dark]) !== ref(v[light])) lines.dark.push(`  --${t.name}: ${ref(v[dark])};`);
}
for (const t of tokens.shadow?.tokens ?? []) {
  const v = typeof t.value === 'string' ? { [light]: t.value } : t.value;
  lines.light.push(`  --${t.name}: ${v[light]};`);
  if (v[dark] !== undefined && v[dark] !== v[light]) lines.dark.push(`  --${t.name}: ${v[dark]};`);
}
const plain = [];
for (const fam of ['spacing', 'radius']) for (const t of tokens[fam]?.tokens ?? []) plain.push(`  --${t.name}: ${t.value};`);
// The design names fonts "Inter" etc.; the self-hosted @fontsource variable fonts register as "Inter Variable".
// Put the registered name first so the bundled file is used, and keep the design's stack as the fallback.
const FONT_FILES = { Inter: 'Inter Variable', 'Plus Jakarta Sans': 'Plus Jakarta Sans Variable', 'JetBrains Mono': 'JetBrains Mono Variable' };
for (const [name, value] of Object.entries(tokens.type.families)) {
  const first = value.match(/^"([^"]+)"|^([A-Za-z]+)/);
  const family = first?.[1] ?? first?.[2];
  const registered = family && FONT_FILES[family] ? `"${FONT_FILES[family]}", ` : '';
  plain.push(`  --font-${name}: ${registered}${value};`);
}

const css = `/* GENERATED by scripts/gen-tokens.mjs from design/tokens.json. Do not edit by hand. */
:root {
  color-scheme: light;
${[...lines.light, ...plain].join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${lines.dark.map((l) => '  ' + l).join('\n')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${lines.dark.join('\n')}
}
`;
writeFileSync(join(root, 'styles/tokens.css'), css);
console.log(`tokens.css: ${lines.light.length} light, ${lines.dark.length} dark, ${plain.length} static`);
